const menuList = [
    {
        title:'首页',
        key:'/home'
    },
    {
      title:'设备管理',
      key:'/dev',
        children:[
            {
                title:'声卡管理',
                key:'/dev/soundcard'
            }
        ]
    },
    {
      title:'猪舍管理',
      key:'/pigpen',
        children:[
            {
                title:'猪舍管理',
                key:'/pigpen/pigmg'
            },
            {
                title:'批次管理',
                key:'/pigpen/batch'
            }
        ]
    },
    {
      title:'语音分析',
      key:'/analysis',
        children:[
            {
                title:'分析结果',
                key:'/analysis/result'
            },
            {
                title:'分析日志',
                key:'/analysis/logs'
            },
            {
                title:'引擎管理',
                key:'/analysis/engine'
            }
        ]
    },
    {
      title:'系统设置',
      key:'/system',
        children:[
            {
                title:'日志管理',
                key:'/system/logs'
            },
            {
                title:'系统参数设置',
                key:'/system/params'
            }
        ]
    },
    {
        title:'UI',
        key:'/ui',
        children:[
            {
                title:'按钮',
                key:'/ui/buttons',
            },
            {
                title:'弹框',
                key:'/ui/modals',
            },
            {
                title:'Loading',
                key:'/ui/loadings',
            },
            {
                title:'通知提醒',
                key:'/ui/notification',
            },
            {
                title:'全局Message',
                key:'/ui/messages',
            },
            {
                title:'Tab页签',
                key:'/ui/tabs',
            },
            {
                title:'图片画廊',
                key:'/ui/gallery',
            },
            {
                title:'轮播图',
                key:'/ui/carousel',
            }
        ]
    },
    {
        title:'表单',
        key:'/form',
        children:[
            {
                title:'登录',
                key:'/form/login',
            },
            {
                title:'注册',
                key:'/form/reg',
            }
        ]
    },
    {
        title:'表格',
        key:'/table',
        children:[
            {
                title:'基础表格',
                key:'/table/basic',
            },
            {
                title:'高级表格',
                key:'/table/high',
            }
        ]
    },
    {
        title:'富文本',
        key:'/rich'
    },
    {
        title:'城市管理',
        key:'/city'
    },
    {
        title:'订单管理',
        key:'/order',
        btnList:[
            {
                title:'订单详情',
                key:'detail'
            },
            {
                title:'结束订单',
                key:'finish'
            }
        ]
    },
    {
        title:'员工管理',
        key:'/user'
    },
    {
        title:'车辆地图',
        key:'/bikeMap'
    },
    {
        title:'图标',
        key:'/charts',
        children:[
            {
                title:'柱形图',
                key:'/charts/bar'
            },
            {
                title:'饼图',
                key:'/charts/pie'
            },
            {
                title:'折线图',
                key:'/charts/line'
            },
        ]
    },
    {
        title:'权限设置',
        key:'/permission'
    },
];
export default menuList;